package com.neo2.telebang.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.neo2.telebang.greendao.DBKeyword;
import com.neo2.telebang.greendao.DBWishListVideo;
import com.neo2.telebang.greendao.DBVideoDownload;

import com.neo2.telebang.greendao.DBKeywordDao;
import com.neo2.telebang.greendao.DBWishListVideoDao;
import com.neo2.telebang.greendao.DBVideoDownloadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBKeywordDaoConfig;
    private final DaoConfig dBWishListVideoDaoConfig;
    private final DaoConfig dBVideoDownloadDaoConfig;

    private final DBKeywordDao dBKeywordDao;
    private final DBWishListVideoDao dBWishListVideoDao;
    private final DBVideoDownloadDao dBVideoDownloadDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBKeywordDaoConfig = daoConfigMap.get(DBKeywordDao.class).clone();
        dBKeywordDaoConfig.initIdentityScope(type);

        dBWishListVideoDaoConfig = daoConfigMap.get(DBWishListVideoDao.class).clone();
        dBWishListVideoDaoConfig.initIdentityScope(type);

        dBVideoDownloadDaoConfig = daoConfigMap.get(DBVideoDownloadDao.class).clone();
        dBVideoDownloadDaoConfig.initIdentityScope(type);

        dBKeywordDao = new DBKeywordDao(dBKeywordDaoConfig, this);
        dBWishListVideoDao = new DBWishListVideoDao(dBWishListVideoDaoConfig, this);
        dBVideoDownloadDao = new DBVideoDownloadDao(dBVideoDownloadDaoConfig, this);

        registerDao(DBKeyword.class, dBKeywordDao);
        registerDao(DBWishListVideo.class, dBWishListVideoDao);
        registerDao(DBVideoDownload.class, dBVideoDownloadDao);
    }
    
    public void clear() {
        dBKeywordDaoConfig.clearIdentityScope();
        dBWishListVideoDaoConfig.clearIdentityScope();
        dBVideoDownloadDaoConfig.clearIdentityScope();
    }

    public DBKeywordDao getDBKeywordDao() {
        return dBKeywordDao;
    }

    public DBWishListVideoDao getDBWishListVideoDao() {
        return dBWishListVideoDao;
    }

    public DBVideoDownloadDao getDBVideoDownloadDao() {
        return dBVideoDownloadDao;
    }

}
