package com.neo2.telebang.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DBVIDEO_DOWNLOAD".
*/
public class DBVideoDownloadDao extends AbstractDao<DBVideoDownload, Long> {

    public static final String TABLENAME = "DBVIDEO_DOWNLOAD";

    /**
     * Properties of entity DBVideoDownload.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VideoID = new Property(1, int.class, "VideoID", false, "VIDEO_ID");
        public final static Property VideoName = new Property(2, String.class, "VideoName", false, "VIDEO_NAME");
        public final static Property VideoCategory = new Property(3, String.class, "VideoCategory", false, "VIDEO_CATEGORY");
        public final static Property VideoCreateAt = new Property(4, String.class, "VideoCreateAt", false, "VIDEO_CREATE_AT");
        public final static Property VideoPath = new Property(5, String.class, "VideoPath", false, "VIDEO_PATH");
    }


    public DBVideoDownloadDao(DaoConfig config) {
        super(config);
    }
    
    public DBVideoDownloadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DBVIDEO_DOWNLOAD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"VIDEO_ID\" INTEGER NOT NULL ," + // 1: VideoID
                "\"VIDEO_NAME\" TEXT NOT NULL ," + // 2: VideoName
                "\"VIDEO_CATEGORY\" TEXT NOT NULL ," + // 3: VideoCategory
                "\"VIDEO_CREATE_AT\" TEXT NOT NULL ," + // 4: VideoCreateAt
                "\"VIDEO_PATH\" TEXT NOT NULL );"); // 5: VideoPath
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DBVIDEO_DOWNLOAD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DBVideoDownload entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getVideoID());
        stmt.bindString(3, entity.getVideoName());
        stmt.bindString(4, entity.getVideoCategory());
        stmt.bindString(5, entity.getVideoCreateAt());
        stmt.bindString(6, entity.getVideoPath());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DBVideoDownload entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getVideoID());
        stmt.bindString(3, entity.getVideoName());
        stmt.bindString(4, entity.getVideoCategory());
        stmt.bindString(5, entity.getVideoCreateAt());
        stmt.bindString(6, entity.getVideoPath());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DBVideoDownload readEntity(Cursor cursor, int offset) {
        DBVideoDownload entity = new DBVideoDownload( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // VideoID
            cursor.getString(offset + 2), // VideoName
            cursor.getString(offset + 3), // VideoCategory
            cursor.getString(offset + 4), // VideoCreateAt
            cursor.getString(offset + 5) // VideoPath
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DBVideoDownload entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVideoID(cursor.getInt(offset + 1));
        entity.setVideoName(cursor.getString(offset + 2));
        entity.setVideoCategory(cursor.getString(offset + 3));
        entity.setVideoCreateAt(cursor.getString(offset + 4));
        entity.setVideoPath(cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DBVideoDownload entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DBVideoDownload entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DBVideoDownload entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
