package com.neo2.telebang.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DBVIDEO_DOWNLOAD".
 */
@Entity
public class DBVideoDownload {

    @Id
    private Long id;
    private int VideoID;

    @NotNull
    private String VideoName;

    @NotNull
    private String VideoCategory;

    @NotNull
    private String VideoCreateAt;

    @NotNull
    private String VideoPath;

    @Generated
    public DBVideoDownload() {
    }

    public DBVideoDownload(Long id) {
        this.id = id;
    }

    @Generated
    public DBVideoDownload(Long id, int VideoID, String VideoName, String VideoCategory, String VideoCreateAt, String VideoPath) {
        this.id = id;
        this.VideoID = VideoID;
        this.VideoName = VideoName;
        this.VideoCategory = VideoCategory;
        this.VideoCreateAt = VideoCreateAt;
        this.VideoPath = VideoPath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getVideoID() {
        return VideoID;
    }

    public void setVideoID(int VideoID) {
        this.VideoID = VideoID;
    }

    @NotNull
    public String getVideoName() {
        return VideoName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoName(@NotNull String VideoName) {
        this.VideoName = VideoName;
    }

    @NotNull
    public String getVideoCategory() {
        return VideoCategory;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoCategory(@NotNull String VideoCategory) {
        this.VideoCategory = VideoCategory;
    }

    @NotNull
    public String getVideoCreateAt() {
        return VideoCreateAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoCreateAt(@NotNull String VideoCreateAt) {
        this.VideoCreateAt = VideoCreateAt;
    }

    @NotNull
    public String getVideoPath() {
        return VideoPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoPath(@NotNull String VideoPath) {
        this.VideoPath = VideoPath;
    }

}
