package com.inspius.yo365.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DBWISH_LIST_VIDEO".
 */
@Entity
public class DBWishListVideo {

    @Id
    private Long id;
    private int VideoID;

    @NotNull
    private String VideoCategory;

    @NotNull
    private String VideoThumbnail;

    @NotNull
    private String VideoName;

    @NotNull
    private String VideoCreateAt;
    private int UserID;

    @Generated
    public DBWishListVideo() {
    }

    public DBWishListVideo(Long id) {
        this.id = id;
    }

    @Generated
    public DBWishListVideo(Long id, int VideoID, String VideoCategory, String VideoThumbnail, String VideoName, String VideoCreateAt, int UserID) {
        this.id = id;
        this.VideoID = VideoID;
        this.VideoCategory = VideoCategory;
        this.VideoThumbnail = VideoThumbnail;
        this.VideoName = VideoName;
        this.VideoCreateAt = VideoCreateAt;
        this.UserID = UserID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getVideoID() {
        return VideoID;
    }

    public void setVideoID(int VideoID) {
        this.VideoID = VideoID;
    }

    @NotNull
    public String getVideoCategory() {
        return VideoCategory;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoCategory(@NotNull String VideoCategory) {
        this.VideoCategory = VideoCategory;
    }

    @NotNull
    public String getVideoThumbnail() {
        return VideoThumbnail;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoThumbnail(@NotNull String VideoThumbnail) {
        this.VideoThumbnail = VideoThumbnail;
    }

    @NotNull
    public String getVideoName() {
        return VideoName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoName(@NotNull String VideoName) {
        this.VideoName = VideoName;
    }

    @NotNull
    public String getVideoCreateAt() {
        return VideoCreateAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideoCreateAt(@NotNull String VideoCreateAt) {
        this.VideoCreateAt = VideoCreateAt;
    }

    public int getUserID() {
        return UserID;
    }

    public void setUserID(int UserID) {
        this.UserID = UserID;
    }

}
